# Build a unitypackage containing all required data for LTCGI
name: Unity Package Build (master)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: at.pimaker.ltcgi/
          lfs: true

      - name: "Copy unitypackage-adapter-protv.list"
        run: cp at.pimaker.ltcgi/unitypackage-adapter-protv.list .
      - name: "Copy unitypackage-adapter-usharp.list"
        run: cp at.pimaker.ltcgi/unitypackage-adapter-usharp.list .

      - name: "Put into Assets/ folder"
        run: mkdir -p Assets/_pi_ && mv at.pimaker.ltcgi/~Adapters Assets/_pi_/_LTCGI-Adapters

      - name: "Rename disabled assets"
        run: |
          mv Assets/_pi_/_LTCGI-Adapters/LTCGI_ProTvAdapter.asset_disabled Assets/_pi_/_LTCGI-Adapters/LTCGI_ProTvAdapter.asset
          mv Assets/_pi_/_LTCGI-Adapters/LTCGI_ProTvAdapter.asset_disabled.meta Assets/_pi_/_LTCGI-Adapters/LTCGI_ProTvAdapter.asset.meta
          mv Assets/_pi_/_LTCGI-Adapters/LTCGI_USharpVideoAdapter.asset_disabled Assets/_pi_/_LTCGI-Adapters/LTCGI_USharpVideoAdapter.asset
          mv Assets/_pi_/_LTCGI-Adapters/LTCGI_USharpVideoAdapter.asset_disabled.meta Assets/_pi_/_LTCGI-Adapters/LTCGI_USharpVideoAdapter.asset.meta

      - name: "Inspect structure"
        run: ls -R Assets/
      
      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: "ltcgi-adapter-protv-${{ github.sha }}.unitypackage"
          include-files: unitypackage-adapter-protv.list

      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: "ltcgi-adapter-usharp-${{ github.sha }}.unitypackage"
          include-files: unitypackage-adapter-usharp.list

      - name: List created unitypackages
        run: find . -iname "*.unitypackage"

      - uses: actions/upload-artifact@v2
        with:
          name: "ltcgi-adapter-protv-${{ github.sha }}.unitypackage"
          path: "ltcgi-adapter-protv-${{ github.sha }}.unitypackage"
      - uses: actions/upload-artifact@v2
        with:
          name: "ltcgi-adapter-usharp-${{ github.sha }}.unitypackage"
          path: "ltcgi-adapter-usharp-${{ github.sha }}.unitypackage"
